import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Твой день",
  description: "Generated by create next app",
  icons: {
    icon: "/birthday/gift.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <link rel="icon" href="/birthday/favicon.ico" sizes="any" /> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#EDE3DA]`}
      >
        {children}
      </body>
    </html>
  );
}
